apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: agent-demo
    app.kubernetes.io/part-of: scale-agent
  name: {{ include "scale-agent.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "scale-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "scale-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: agent-demo
    app.kubernetes.io/part-of: scale-agent
  name: {{ include "scale-agent.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - namespaces
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  - /metrics/cadvisor
  - /configz
  verbs:
  - get
